version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:5.0.2
    volumes:
      - ./db/:/data/db/
      - ./conf/:/etc/mongo/
      - ./log/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    networks:
      - localhost
    command: --config /etc/mongo/mongod.yml
    restart: always
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${USERNAME}:${PASSWORD}@mongo:27017
      VIRTUAL_HOST: mongo.localhost
      VIRTUAL_PORT: 8081
    networks:
      - localhost
    restart: always
networks:
  localhost:
    external: true
